### PR TITLE
Fix cs and transitions

### PR DESCRIPTION
**Pull request by tvt173**
This PR fixes two cases:

1. Invocation of `pdk.get_cross_section()` on dictionaries, especially for multi-layer cross sections for which the cross_section.copy() hack does not work.
2. Extrusion of transitions between cross sections which do not have 1:1 correlation between layers (i.e. rib to strip)

### CODE REVIEW

**Comment by tvt173** [comment]
looks like it is failing some tests. will have to take a look another time

**Comment by joamatab** [comment]
happy to merge when tests pass

**Comment by tvt173** [comment]
working on it

**Comment by tvt173** [comment]
hi @joamatab, this branch is now fixed and ready to merge. note the updated constraint for transitions between two cross sections: *if a cross section has more than one section on the same layer, each section on that layer must be named in order to be used in a transition*.

in this way, transitions go back to relying on names of sections, only for this case where there is not one unique section per layer. the benefit is that you can transition cross sections which are not exactly the same (before it would rely on ordering of the sections, which is generally not the same for two different cross sections, i.e. a rib to strip transition)

**Comment by joamatab** [comment]
Thank you Troy,

there are still some issues on this notebook

image

https://gdsfactory.github.io/gdsfactory/notebooks/rib_strip_autotransition.html

**Pull request merged**
