### PR TITLE
fix femwell and try to fix meow plugin

### PR DESCRIPTION
**Pull request by joamatab**
- fix femwell installation
- eme plugin still has some issues to simulate a taper

image

### CODE REVIEW

**Comment by simbilod** [comment]
I've noticed that results have a very strong dependence on the simulation parameters (num_modes, resolution, cell_length)

It helps to use negative spacing_y to make the cross_section a bit smaller, and hence require coarser grid, than what the LayerStack would give you by default.

AFAIK basic EME like this needs a lot of slices to avoid spurious reflections due to "staircasing". Commercial EME software usually employ some sort of first-order interpolation scheme to avoid this and converge the results better.

**Comment by simbilod** [comment]
See e.g. 

`   c = gf.components.taper(length=10, width2=2)
    c.show()

    from gdsfactory.tech import get_layer_stack_generic

    filtered_layerstack = LayerStack(
        layers={
            k: get_layer_stack_generic().layers[k]
            for k in (
                "slab90",
                "core",
                "box",
                "clad",
            )
        }
    )

    trans = []
    cells_lengths = [0.1,0.25,0.5,0.75,1]
    for cell_length in cells_lengths:

        m = MEOW(component=c, 
                    layerstack=filtered_layerstack, 
                    wavelength=1.55,
                    resolution_x=100,
                    resolution_y=100,
                    spacing_x=1,
                    spacing_y=-3,
                    num_modes=4,
                    cell_length=cell_length,
                    )
        import matplotlib.pyplot as plt
        # m.plot_mode(xs_num = -1, mode_num = 0)
        # m.plot_cross_section(xs_num = -1)
        sp = m.compute_sparameters()
        te0_trans = np.abs(sp["o1@0,o2@0"])**2
        trans.append(te0_trans)
        # print(len(m.cells))

    plt.plot(cells_lengths, trans)
    plt.title("10um taper, resx = resy = 100, num_modes = 4")
    plt.xlabel("Cell length (um)")
    plt.xlabel("TE0 transmission")
    plt.show()`

image

**Comment by simbilod** [comment]
x-axis should be cell_size from 100 nm to 1 um, and y axis transmission **

**Comment by joamatab** [comment]
This is great 😊 


I see, how about reduce the default cell length to 0.5?

**Comment by simbilod** [comment]
Sure!

**Pull request merged**
