### PR TITLE
Meshwell for 3D meshing

### PR DESCRIPTION
**Pull request by simbilod**
@HelgeGehring 

Experimental more robust 3D meshing with pure gmsh backend

Uses [meshwell](https://github.com/simbilod/meshwell), which is not a requirement yet since it lives mostly on the repo and not in a package

### CODE REVIEW

**Comment by joamatab** [comment]
Looks good Simon, tests are failing, i think we need to add it to pyproject.toml

**Comment by simbilod** [comment]
Ah ok. I'll make a meshwell release and make it optional requirement

**Comment by joamatab** [comment]
still failing

```
from meshwell.prism import Prism
E   ModuleNotFoundError: No module named 'meshwell'
```

**Comment by simbilod** [comment]
looks better!

**Comment by joamatab** [comment]
great, thank you Simon!

**Pull request merged**
