### PR TITLE
Reintroduce font option in `text_rectangular`

### PR DESCRIPTION
**Pull request by 95-martin-orion**
Prior to v8.0, gdsfactory supported alternate fonts. This PR reintroduces that support and "FONT_LITHO".

Compare with [text_rectangular](https://github.com/gdsfactory/gdsfactory/blob/v7.27.0/gdsfactory/components/text_rectangular.py) and [text_rectangular_font](https://github.com/gdsfactory/gdsfactory/blob/v7.27.0/gdsfactory/components/text_rectangular_font.py) from `v7.27.0`.

### CODE REVIEW

**Comment by 95-martin-orion** [comment]
It looks like there's a fair bit that needs to be resolved before merging this. I'm willing to take a shot at that once I have confirmation that this is a valid addition in the v8.* world.

**Comment by 95-martin-orion** [comment]
Bumping this PR - @joamatab, is this a valid addition to gdsfactory v8? If so I'm happy to resolve the failing tests, but any pointers would be welcome.

**Comment by joamatab** [comment]
Hi Orion,

I think this functionality is already in the main branch

**Comment by joamatab** [comment]
addressed here

https://github.com/gdsfactory/gdsfactory/pull/3143

**Pull request closed without merging**
