### PR TITLE
avoid dollars when watching python files

### PR DESCRIPTION
**Pull request by joamatab**

### CODE REVIEW

**Comment by tvt173** [comment]
what's the issue/goal of this PR? I don't think the fix in here is very good, because it won't cache or increment the name counter the first time a component with a given name is defined, right?

**Comment by joamatab** [comment]
Sorry, I'm still working on it 

When using the file watcher we always get incremental numbers

**Comment by joamatab** [comment]
now it is ready to review

@tvt173

**Comment by joamatab** [comment]
Going for this PR instead

https://github.com/gdsfactory/gdsfactory/pull/2300

**Pull request closed without merging**
