### PR TITLE
Fix Type Hints

### PR DESCRIPTION
**Pull request by MatthewMckee4**
## Summary by Sourcery

Fix type hints across multiple functions by specifying 'Any' for '**kwargs' and refactor routing strategy definitions to use type aliases for improved code clarity.

Bug Fixes:
- Correct type hints for various functions by specifying 'Any' for '**kwargs' to ensure proper type checking and avoid potential runtime errors.

Enhancements:
- Add more ruff linting rules

Design Choices:
- Add more TypeAlias like 'Size', 'Delta' and 'Spacing' for widely used types to improve readability and maintainability.

### CODE REVIEW

**Comment by MatthewMckee4** [comment]
This function has incorrect type hinting and does not work unless you set default pdk to one which has that function
image
Not really sure how to fix the type hints, perhaps we consider removing this?

**Comment by sebastian-goeldi** [comment]
I would suggest to make it raise an error if not implemented by the pdk. that way it will always work and will pass the type checker

**Comment by MatthewMckee4** [comment]
I understand this PR will be very hard to review as there is already 98 files changed, is there a preferred way to work with this size of change to the repo?

**Comment by joamatab** [comment]
We can merge it and continue the work on separate PRs

**Comment by MatthewMckee4** [comment]
Sounds good, since they are all independent changes this should be good to be merged. Only thing I will say is that the extra ruff linting rules mean that the code base fails with >400 errors. I will let you make the decision, as fixing these errors will add many more changes and will take at least a week on my end.

**Review by joamatab — APPROVED** [review]

**Pull request merged**
