### PR TITLE
Load gdsfactory config from pyproject.toml

### PR DESCRIPTION
**Pull request by thomasdorch**
Allows us to add gdsfactory configuration settings to the `[tool.gdsfactory]` block in pyproject.toml files. 

Will load parameters for the `Settings` object if there is a `pyproject.toml` in the same directory as the first file that imports gdsfactory in the call stack.

For example, we can use it to pin config settings in a mask repo:
```
[project]
name = "example-chip"
version = "0.0.1"

[tool.gdsfactory]
pdk = "ubcpdk"
allow_offgrid = true
```
I would also like to add the gds write settings here but going any further than this might get complicated quickly so I want to get this bit out there first to see if others like having this option.

### CODE REVIEW

**Comment by thomasdorch** [comment]
Is there an example somewhere for the dotenv config? I don't see anything about it in the docs..

But the point of doing it with the pyproject is to avoid having different config files for different tools, so we can have the project dependencies, ruff, pytest, and gdsfactory configs all in one place.

**Comment by joamatab** [comment]
let me add some docs, the nice thing of dotenvs is that you can have different ones per folder, in case you want multiple projects with different settings

**Comment by joamatab** [comment]
i added some docs [here](https://github.com/gdsfactory/gdsfactory/pull/2608/commits/6fffee974a18497ce1627bd604d86e6f27b34668)

**Comment by joamatab** [comment]
I'll close this for now, we can always bring it back if we find it better than the dotenv approach

**Comment by thomasdorch** [comment]
@joamatab thanks for putting the docs together. I agree the .env is a good way to do the gdsfactory config. I still think adding it to pyproject would be a nice option as well but we can revisit later

**Pull request closed without merging**
