### PR TITLE
Works with simphony latest

### PR DESCRIPTION
**Pull request by SkandanC**
Most of the tests which were failing have been fixed. 

Major changes:

- Modify import statements to work with latest simphony
- Change simphony components generated using SimphonyWrapper and SiPANN components to components from simphony's sipann library

Tests still failing:

- Some tests require .dat files which was missing on my fork 
- gdsfactory/simulation/simphony/test_circuits.py [ring_single] - The s-parameters generated after my fix are very close (~0.95) to the ideal values of 1. I am still working on getting these fixed

### CODE REVIEW

**Comment by joamatab** [comment]
amazing! thank you @SkandanC 

we may require to add some tests to the gdslib repo

**Comment by SkandanC** [comment]
> amazing! thank you @SkandanC
> 
> we may require to add some tests to the gdslib repo

Thank you. Could you tell me more about this? And would you need me to do anything for this?

**Comment by joamatab** [comment]
yes, if you install gdsfactory with `install.sh` or `install.bat` it should download the `gdslib` repo

https://github.com/gdsfactory/gdslib

which contains the reference files for the tests

**Comment by joamatab** [comment]
I have to revert this as it is still not working

I created a branch and an issue to track 
https://github.com/gdsfactory/gdsfactory/issues/388

**Pull request merged**
