### PR TITLE
Sweep Fabrication

### PR DESCRIPTION
**Pull request by simbilod**
some cleaned up work I had lying around to treat morphological transformations as parameters to the model builder, e.g.

Initial geometry:

image

Dilation and erosion (ports are shrunk and grown too):

image

Offsets between layers (ports are also translated):

image

Corner rounding (ports are padded to maintain continuity):

image

This can be swept just like any other Component or LayerStack parameters in the model builder:

image

Next step is to include better distributed processing in the generic model builder. I think with Ray we can scale from local, to cluster, to cloud seamlessly, so just need to format the remote decorator properly

### CODE REVIEW

**Comment by joamatab** [comment]
Looks great Simon,

I think you should merge the polygons before rounding them

**Comment by joamatab** [comment]
The docs also have some issues, can merge once it's fixed

https://github.com/gdsfactory/gdsfactory/actions/runs/4218770431/jobs/7323514671

**Comment by simbilod** [comment]
Thanks @joamatab , I was already fusing the polygons for the erosion/dilation so that was an easy addition :)

@HelgeGehring the notebook now crashes because femwell tries to convert something complex to real. The plugin test fails for the same reason. Do you know the easiest fix?

```
Traceback (most recent call last):
  File "/home/simbil/Github/gdsfactory/gdsfactory/simulation/fem/test_mode_solver.py", line 71, in <module>
    test_compute_cross_section_mode_cache()
  File "/home/simbil/Github/gdsfactory/gdsfactory/simulation/fem/test_mode_solver.py", line 56, in test_compute_cross_section_mode_cache
    lams, basis, xs = compute_modes(with_cache=True, overwrite=False)
  File "/home/simbil/Github/gdsfactory/gdsfactory/simulation/fem/test_mode_solver.py", line 35, in compute_modes
    lams, basis, xs = compute_cross_section_modes(
  File "/home/simbil/Github/gdsfactory/gdsfactory/simulation/fem/mode_solver.py", line 63, in compute_cross_section_modes
    return compute_component_slice_modes(
  File "/home/simbil/Github/gdsfactory/gdsfactory/simulation/fem/mode_solver.py", line 191, in compute_component_slice_modes
    lams, basis, xs = mode_solver.compute_modes(
  File "/home/simbil/miniconda3/envs/gdsfactory/lib/python3.10/site-packages/femwell/mode_solver.py", line 83, in compute_modes
    lams, xs = solve(
  File "/home/simbil/miniconda3/envs/gdsfactory/lib/python3.10/site-packages/skfem/utils.py", line 262, in solve
    out = solve_eigen(A, b, x, I, solver, **kwargs)  # type: ignore
  File "/home/simbil/miniconda3/envs/gdsfactory/lib/python3.10/site-packages/skfem/utils.py", line 215, in solve_eigen
    return solver(A, M, **kwargs)
  File "/home/simbil/miniconda3/envs/gdsfactory/lib/python3.10/site-packages/femwell/solver.py", line 114, in solver
    K_ = PETSc.Mat().createAIJ(size=K.shape, csr=(K.indptr, K.indices, K.data))
  File "PETSc/Mat.pyx", line 357, in petsc4py.PETSc.Mat.createAIJ
  File "PETSc/petscmat.pxi", line 823, in petsc4py.PETSc.Mat_AllocAIJ
  File "PETSc/petscmat.pxi", line 794, in petsc4py.PETSc.Mat_AllocAIJ_CSR
  File "include/arraynpy.pxi", line 155, in petsc4py.PETSc.iarray_s
  File "include/arraynpy.pxi", line 130, in petsc4py.PETSc.iarray
TypeError: Cannot cast array data from dtype('complex128') to dtype('float64') according to the rule 'safe'
```

**Comment by HelgeGehring** [comment]
Might it be, that the "real" conversion of slepc is installed instead of the "complex" version?
Also, you can try to not specify the solver (to use scipy)

**Comment by simbilod** [comment]
strange, the gdsfactory makefile installs the complex version

Anyway, I am now making it use whatever is default in femwell and now it works!

**Comment by simbilod** [comment]
seems like scipy works locally but not on the build server for docs

**Comment by simbilod** [comment]
Changed it to slepc again. Worked locally on my VM, and seems to work here too

**Pull request merged**
