### PR TITLE
Adding section based ring generator and L shape waveguide cross sections

### PR DESCRIPTION
**Pull request by mdecea**
Added a class to generate ring resonators based on specifying different sections with a certain angular extent. This should be useful for interleaved junction rings or in general any ring with a non-standard junction design.

### CODE REVIEW

**Comment by mdecea** [comment]
@simbilod check it out, might be useful

**Comment by simbilod** [comment]
Nice!

I would just change the logic to place the bus at the end to consider the position of the ring and bus waveguiding layers instead of component. 

A lot of the more fun cross_sections have big offset that throw off the component coordinates:

image

With my fix it gets the gap right:

image

**Comment by simbilod** [comment]
I'm having issues pushing to this PR because I don't seem to have write access to the main branches of this or your repo, but here is the code you can change to do what I show:

`    
<above here is good>

   # Rotate so that the first section is centered at the add bus
    if init_cross_section is not None:
        ring = ring.rotate(
            -init_angle / 2
        )  # also change the component for later bound extraction
        r.rotate(-init_angle / 2)
    else:
        ring = ring.rotate(-cross_sections_angles[0] / 2)
        r.rotate(-cross_sections_angles[0] / 2)

    # Add bus waveguides

    # Figure out main waveguiding layer of the ring at the ring-bus interface
    input_xs_layer = (
        gf.get_cross_section(init_cross_section).layer
        if init_cross_section
        else gf.get_cross_section(cross_sections[cross_sections_sequence[0]]).layer
    )
    ring_guide = ring.extract([input_xs_layer])

    print(ring_guide.ymin)

    # Add bus waveguides
    s = straight(length=ring.xsize, cross_section=bus_cross_section)

    # Figure out main waveguiding layer of the bus at the ring-bus interface
    input_xs_width = gf.get_cross_section(bus_cross_section).width

    s_add = c << s
    s_add.x = r.x
    s_add.ymax = ring_guide.ymin - gap + s.ysize / 2 - input_xs_width / 2

    if add_drop:
        s_drop = c << s
        s_drop.x = r.x
        s_drop.ymin = ring_guide.ymax + gap - s.ysize / 2 + input_xs_width / 2

    return c
`

**Comment by mdecea** [comment]
Made a new commit with your code. Thanks @simbilod, this definitely makes it better!

**Comment by joamatab** [comment]
Thank you Simon and Marc,

I also add you directly to the repo with write access, so you can now push directly to the PRs and branches

I will merge it and release a new version

**Pull request merged**
