### PR TITLE
raise error for locked components

### PR DESCRIPTION
**Pull request by joamatab**
fixes  https://github.com/gdsfactory/gdsfactory/issues/3553

Raises error if cell is locked

## Summary by Sourcery

Prevent modification of cached components by raising a LockedError.

Bug Fixes:
- Fix issue where cached components could be modified, leading to inconsistencies.

Tests:
- Add tests to verify that a LockedError is raised when attempting to modify a cached component.

### CODE REVIEW

**Comment by MatthewMckee4** [comment]
Just looking into some functions that may be affected by this
```python
component = gf.get_component(component)

if component._locked:
    component = component.copy()
```
Do we think this would be an appropriate addition?

**Comment by joamatab** [comment]
I think we should discourage bad behavior so it's okay to raise an error instead of magically make a copy

**Comment by MatthewMckee4** [comment]
So the proper functionality should be:
```python
c = bend_circular().copy()
gf.add_padding(c, default=10)
```
?
for the example i showed in the issue

**Comment by joamatab** [comment]
For one off cases yes, but in most cases you will do

```python
@gf.cell
def bend_with_padding(radius=5):
    c = gf.components.bend_circular(radius=radius)
    c_with_padding = c.copy()
    gf.add_padding(c_with_padding)
    return c_with_padding
```

**Comment by joamatab** [comment]
but maybe what you are suggesting is a bit more user friendly, what do you think?

**Comment by MatthewMckee4** [comment]
I have in idea, I'll write it up and get back to you asap

**Comment by MatthewMckee4** [comment]
Something like this? Could be used anywhere where a modification needs to be made to the component
```python
def get_unlocked_component(
    component: ComponentSpec, settings: dict[str, Any] | None = None, **kwargs: Any
) -> Component:
    c = get_component(component, settings, **kwargs)
    if c._locked:
        warnings.warn("Component is locked, copying and unlocking")
        c = c.copy()
        c._locked = False
    return c
```

**Comment by MatthewMckee4** [comment]
In fact copy already sets locked to false, so can remove that

**Comment by flaport** [comment]
I dont like warnings being raised if you explicitly ask for an unlocked componen. Just leave the warning out IMO

**Comment by flaport** [comment]
I think this function should not be added. Its confusing. Just copy the function of it's locked .

**Comment by joamatab** [comment]
I tend to prefer discouraging potentially problematic behavior, so perhaps we can leave that "magic" out for now.

**Comment by joamatab** [comment]
I'll close this one as we have now this other PR

https://github.com/gdsfactory/gdsfactory/pull/3556

**Pull request closed without merging**
