### PR TITLE
Mesh profile per layer

### PR DESCRIPTION
**Pull request by simbilod**
* New "buffer_profile" argument in `LayerLevel` that is used to parametrize arbitrary transformations for a layer when it needs to be represented in a simulator.

For instance, one can assign a round-ish profile (better with more points)  to a specific GDS layer in this way:

```
            undercut=LayerLevel(
                layer=LAYER.UNDERCUT,
                thickness=-undercut_thickness,
                zmin=-box_thickness,
                material="air",
                buffer_profile=[[0, 0.3, 0.6, 0.8, 0.9, 1], [-0, -0.5, -1, -1.5, -2, -2.5]],
                info={"mesh_order": 1},
            ),
```

The `buffer_profile` is a tuple of two lists. The first one parametrizes a position from zmin (when = 0) to zmin + thickness (when = 1). The second parametrizes a shrink (for negative sign) or expansion (if positive) to apply to this layer's polygons.

For the following waveguide layout with the middle square being an undercut:

```
    from gdsfactory.tech import get_layer_stack_generic

    c = gf.component.Component()

    waveguide = c << gf.get_component(gf.components.straight_pin(length=10, taper=None))
    undercut = c << gf.get_component(gf.components.rectangle(size = (5.0, 5.0),
                                                                layer = "UNDERCUT",
                                                                centered = True,)
                                                                ).move(destination=[4,0])
    c.show()

    filtered_layerstack = LayerStack(
        layers={
            k: get_layer_stack_generic().layers[k]
            for k in (
                "slab90",
                "core",
                "via_contact",
                "undercut",
                "box",
                "substrate",
                "clad",
                "metal1",
            ) 
        }
    )

    resolutions = {}
    resolutions["core"] = {"resolution": 0.05, "distance": 2}
    resolutions["slab90"] = {"resolution": 0.03, "distance": 1}
    resolutions["via_contact"] = {"resolution": 0.1, "distance": 1}

    geometry = uz_xsection_mesh(
        c,
        [(4, -15), (4, 15)],
        filtered_layerstack,
        resolutions=resolutions,
        # background_tag="Oxide",
        filename="mesh.msh",
    )
```

image

the following cross-sectional mesh is obtained along the` x=4` line (with different colors = different GDS layers, that a simulator can parse)

image

* The zmin, thickness, and sidewalls arguments were kept, but are now used to generate rectangular or slanted `buffer_profiles`
* LayerLevel also now accepts a "None" layer, which assigns a polygon of the shape `bbox` to this layer if layer is present. Currently used for substrate, BOX, and cladding.

@joamatab There is duplication with the recent definition of BOX at the global `LayerStack` level. I think we should let BOX, substrate, etc. be regular LayerLevels that have `layer=None` so that all other parameters of a layer (zmin, thickness, material, mesh_order, etc) can also be assigned to them, and they can be treated like regular layers in code, including being filtered out or added to a `LayerStack`.

@HelgeGehring

### CODE REVIEW

**Comment by joamatab** [comment]
agreed on the box_layer, 

buffer_profile is a bit confusing name
how about `z_to_bias`?

**Comment by simbilod** [comment]
Sure I'll change it later tonight!


Obtenir Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by joamatab** [comment]
I'll send a PR

**Comment by simbilod** [comment]
Ok -- there's only tests for simple cases right now so it might not catch all of these. Since the tool is getting more into shape I'll start adding more tests too

 pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by joamatab** [comment]
Also,

How can we draw layers with layer=None in any of the simulation plugins?

**Comment by simbilod** [comment]
For the gmsh plugin they are assigned a polygon of size bbox

Ultimately the plugin developer has to decide

Obtenir Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Pull request merged**
