### PR TITLE
Pydantic v2 

### PR DESCRIPTION
**Pull request by joamatab**
More Contributions are welcome

### CODE REVIEW

**Comment by dmontagu** [comment]
Hey, just want to add a few things:
* In the next release (and currently on main branch of pydantic), there will be `pydantic.v1` which will have everything from pydantic v1 without modifications (though may be slower as it will not be cython-compiled). This may help you transition more incrementally
* One of the things I changed in my original PR was to get rid of the custom `__init__` in favor of root validators and some other weird things. But we went back on that change and have since added support for custom `__init__`, so you might be able to undo those changes and keep the custom `__init__` unmodified. I haven't confirmed that.

We are nearing the feature-freeze "beta" release, hopefully happening within the next week. Once that happens I'll be happy to take another pass.

**Comment by daquintero** [comment]
Yes I agree with your points too David! When I saw your branch changes I realised that the way I was attempting to refactor was probably not the ideal future compatibility like you added. 

Am happy to do as you suggest in terms of changes if I can help (as I do have an interest of getting this working too) although if the new release is soon then also happy to wait and help how I can later if needed!

**Comment by daquintero** [comment]
I was also thinking after the refactor, that there were quite a few classes that had a lot of repeated pydantic code. For the sake of maintenance, future integration, and debugging one thing we could do is have a set of generic `Validator` classes that implement a standard config, and common classes inherit from them. There are also some validators that may need proper implementation I think with usage of some plugins as input parameters usage from what I remember being involved too.

**Comment by daquintero** [comment]
Hi David and Joaqin,

I have done anotehr clean go at the porting using the migration protocol described in https://github.com/pydantic/pydantic/issues/5771 which I think seems to work.

It mostly involved changing the imports from `pydantic` to `pydantic.v1` as David suggested. I am doing it so I can get my project fully integrated. It works from the latest github pydantic v2 version and I reckon this has already been deployed to PyPi, but I did un the migration_v1.sh script provided in my environment and I don't know if that is already automated on PyPi install. 

In any case, in case it is useful, I have made a pull request here https://github.com/gdsfactory/gdsfactory/pull/1718. Pytest seems to complete and not dissimilar from the current `main` pytest.

**Pull request closed without merging**
