### PR TITLE
Updated schematic library to graphviz

### PR DESCRIPTION
**Pull request by Jelly298**
This pull request updates the schematic library to graphviz, which improves the visualization of schematics. 

Please review the changes, and let me know if any adjustments are needed. I also plan to update the documentation to reflect these enhancements once the pull request is approved.

## Summary by Sourcery

Update the schematic library to use Graphviz for better visualization of schematics, replacing the previous networkx implementation. Add Graphviz as a new dependency in the project.

Enhancements:
- Replace networkx with Graphviz for improved schematic visualization.

Build:
- Add Graphviz as a new dependency in the project.

### CODE REVIEW

**Comment by sebastian-goeldi** [comment]
I think one of the big downsides of graphviz is that it depends on system libraries. This is all fine and dandy for power users. But for the inexperienced python users of gdsfactory, I think it's a bit much, especially if you look at the adventure for windows users https://pygraphviz.github.io/documentation/stable/install.html (if it's native python).

**Comment by Jelly298** [comment]
I understand your point; are there any alternative and simpler to use libraries? The issue is that while networkx provides convenience, the graphs often appear cluttered and the text placement is not optimal

**Comment by sebastian-goeldi** [comment]
We could make it an optional dependency and add a separate submodule for it.

**Comment by joamatab** [comment]
it looks really nice

image


How could we make the ports show up as part of the component? something like this

image

**Comment by Jelly298** [comment]
Screenshot 2024-11-07 at 12 08 26 AM
Screenshot 2024-11-07 at 12 09 04 AM

I attempted to use the record structure in graphviz to create the effect (not pushed yet). Is this what you mean to show ports as part of the component?

**Comment by joamatab** [comment]
yes, that looks amazing!

**Comment by joamatab** [comment]
Also, it would be great if we can plot in a jupyter-notebook

```
c.plot_netlist() 
```

would plot the graphviz plot

and 

```
c.get_netlist_graph()
```

returns the graphviz representation of the graph

**Comment by sebastian-goeldi** [comment]
Can we stop calling stuff netlist that is not a netlist? :upside_down_face:

**Comment by Jelly298** [comment]
Let me update the docstrings. I think I messed up some merging.

**Comment by Jelly298** [comment]
Um after some searching, I am not too sure what to change for netlists ...

Also @joamatab I’ve updated the graphviz display so that it shows inline when running in Jupyter, and as a PNG otherwise. The same behavior applies to the NetworkX fallback. Moreover, I added an extra parameter to toggle the visibility of ports.

**Review by joamatab — APPROVED** [review]
looks great!

**Pull request merged**
