### PR TITLE
fix application of pdk default_decorator

### PR DESCRIPTION
**Pull request by tvt173**
hi @joamatab , it seems like in 7.8.12 support for PDK `default_decorator` was dropped. this PR restores that functionality and adds a test

### CODE REVIEW

**Comment by tvt173** [comment]
@joamatab it seems like some side effects have started occuring lately, which seem to be unrelated to these changes. have you noticed this? notice the test I added but skipped. having it run caused more failed tests. you can see with it skipped, there are failed tests on MacOS, but not ubuntu. i get unpredictable results locally on windows with it sometimes failing 0, 1, or 2 times, seemingly at random. it seems to have to do with the child metadata and naming of cells with children

**Comment by tvt173** [comment]
i fixed the above issue by deepcopying settings and info from the child cells. however, i still get some strange minor side effects from the new test added, so i have left it skipped

**Comment by joamatab** [comment]
thank you for the fix Troy!

yes, we've noticed strange behaviour with tests failing in some OS not being repeatable

@yaugenst

**Comment by joamatab** [comment]
As you pointed out, decorators are causing side effects

**Comment by tvt173** [comment]
> As you pointed out, decorators are causing side effects

@joamatab , to be clear, it's actually _not_ the decorator which is causing side effects. it's **simply the act of clearing the cache midway through the tests which causes side effects**. i proved this to myself by gradually paring down the test to the fundamentals... first, I reduced the original test to a test which simply activates a new PDK (without a default_decorator) briefly, then, without doing anything else, reactivates the original PDK

 ```python
def test_pdk_switch_causes_chaos():
    # let's get the currently active pdk so we can set things back as they were later
    prev_active_pdk = gf.get_active_pdk()

    # create a new pdk and activate it, but don't actually use it at all
    pdk_without_decorator = gf.Pdk(
        name="pdk_without_decorator",
        base_pdk=get_generic_pdk(),
    )
    pdk_without_decorator.activate()

    # look, i'm not even doing anything, besides temporarily switching PDKs!

    # now reset the previously active pdk... watch unrelated tests fail
    prev_active_pdk.activate()
```

you can see that this still causes side effects. i get 3 failed tests... the _same_ 3 I get from the test I added (but skipped) in this PR. you can deduce that this is _either_ due to something particular with the activation/deactivation of PDKs, _or_ it is due to clearing the cache between PDK switches, which will have the net effect of changing the order of invocation of different components, which traditionally has implied side effects due to things like mutability of components after being instantiated. that's why i tried this fix of using deepcopy instead of copy for these child cell settings (where I saw there were some recent changes). that indeed seemed to fix some issues, but not all. you can see that there are still some issues, even if you replace the above test simply with this

```python
def test_clear_cache():
    gf.clear_cache()
```

for me i still get the same 3 failures of unrelated tests after adding this simple test. this indicates to me that the side effects seem to have something more to do with component mutability/the order in which components are invoked

**Pull request merged**
