### PR TITLE
Function for layer_colors -> .lyp file

### PR DESCRIPTION
**Pull request by alexsludds**
I've added a function (which I mostly stole from PHIDL), which takes in a gdsfactory layer_colors object and converts it to a .lyp file. I find .lyp files really useful for sharing gds files with folks who don't use gdsfactory.

### CODE REVIEW

**Comment by alexsludds** [comment]
Big shout out to  Adam McCaughan  since this is mostly his code.

**Comment by joamatab** [comment]
Thank you Alex,

I think we have the same functionality in `gdsfactory/klayout_tech.py `

Thomas has an incoming PR #1014 where he improves this

@thomasdorch

**Comment by alexsludds** [comment]
Awesome! Great to see Thomas has put so much work into this. 
Looking forward to when this is pushed into the main branch.
Feel free to delete this pull request if/when it isn't needed anymore Joaquin.

**Comment by joamatab** [comment]
addressed in https://github.com/gdsfactory/gdsfactory/pull/1102

**Pull request closed without merging**
