### PR TITLE
radius in port properties & arbitrary port orientation FDTD

### PR DESCRIPTION
**Pull request by simbilod**

### CODE REVIEW

**Comment by simbilod** [comment]
Hey @joamatab , do you know why the attributes of my ports could not be transferred when the component is loaded in the extend_ports function?

Code (in derived layer):

```
        print("original component", component.ports)
        component_derived.add_ports(component.ports)
        print("after add_ports", component_derived.ports)
```

Output:

```
original component {'o2': Port (name o2, center [-3.42020143  1.30307379], width 0.5, orientation 160.0, layer (1, 0), port_type optical, radius inf), 'o1': Port (name o1, center [-3.42  0.  ], width 0.5, orientation 180.0, layer (1, 0), port_type optical, radius inf), 'o3': Port (name o3, center [3.42020143 1.30307379], width 0.5, orientation 20.0, layer (1, 0), port_type optical, radius -10.0), 'o4': Port (name o4, center [3.42 0.  ], width 0.5, orientation 0.0, layer (1, 0), port_type optical, radius 10.0)}
after add_ports {'o2': Port (name o2, center [-3.42020143  1.30307379], width 0.5, orientation 160.0, layer (1, 0), port_type optical, radius inf), 'o1': Port (name o1, center [-3.42  0.  ], width 0.5, orientation 180.0, layer (1, 0), port_type optical, radius inf), 'o3': Port (name o3, center [3.42020143 1.30307379], width 0.5, orientation 20.0, layer (1, 0), port_type optical, radius inf), 'o4': Port (name o4, center [3.42 0.  ], width 0.5, orientation 0.0, layer (1, 0), port_type optical, radius inf)}
```

**Comment by joamatab** [comment]
Hi Simon, 

ports already support Optional cross_section, so in principle the radius information can be derived from there,

what do you think?

**Comment by simbilod** [comment]
I want to be able to tell FDTD solvers which bend mode to use. 

The same cross-section could support different radius depending on the component right?

**Comment by joamatab** [comment]
I see, how about using Port.info dict to add these types of things?

**Comment by simbilod** [comment]
Sounds good I'll take this route!

**Pull request closed without merging**
