### PR TITLE
Cell can do partials

### PR DESCRIPTION
**Pull request by joamatab**
allows you to use cell to create partials, and create new function signatures while maintaining IDE autocompletion

```python
straight = gf.components.straight
straight_sc = cell(straight, cross_section="xs_sc", basename="straight_sc")
straight_so = cell(straight, cross_section="xs_so", basename="straight_so")
straight_rc = cell(straight, cross_section="xs_rc", basename="straight_rc")
straight_ro = cell(straight, cross_section="xs_ro", basename="straight_ro")
straight_nc = cell(straight, cross_section="xs_nc", basename="straight_nc")
straight_no = cell(straight, cross_section="xs_no", basename="straight_no")
```

fixes https://github.com/gdsfactory/gdsfactory/issues/2609 in a more elegant way

### CODE REVIEW

**Comment by tvt173** [comment]
I think this is much nicer than just using a regular partial. These are my only concerns:

1. Versus _rewriting the function definition in each case_, a downside will still be that the docs for the cell are not tailored to each function. Of course, this is no better or worse than a partial, but still results in something less polished than if you were to write a function wrapper for each case (or only maintain one function for the PDK with a string arg for each case). I suppose you could get around this though by providing a `doc` argument or something like that.
2. I'm not sure it's best to conflate all this into `cell` directly vs creating a separate function (i.e. `partial_cell`) for this purpose. I'm concerned of edge cases and user confusion if we let `cell` become overly complicated... I suppose it's ok though and might be more difficult to implement otherwise. Thoughts?

**Comment by flaport** [comment]
derived_cell?

**Comment by joamatab** [comment]
That's a good name

**Comment by joamatab** [comment]
the issue is that it would require maintaining 2 cell decorators, so maybe keeping one only makes things easier

@sebastian-goeldi

**Comment by joamatab** [comment]
maybe this is too hacky and shoulnd't be merged, as it won't be compatible with the future kfactory backend,

i'll mark it as draft

@nikosavola

**Pull request closed without merging**
