### PR TITLE
manhattanization

### PR DESCRIPTION
**Pull request by simbilod**
Pure Python manhattanization (inefficient, but works)

image

### CODE REVIEW

**Comment by simbilod** [comment]
also added to route_quad, and tests

**Comment by joamatab** [comment]
Thank you Simon!

fixes #1509

**Comment by tvt173** [comment]
hi @simbilod , this may be a good use case for numba jit?
https://numba.pydata.org/numba-doc/latest/user/5minguide.html#will-numba-work-for-my-code

i think you may need to convert the polygons to numpy arrays first, but then i think it should be pretty fast...

**Comment by simbilod** [comment]
> hi @simbilod , this may be a good use case for numba jit? https://numba.pydata.org/numba-doc/latest/user/5minguide.html#will-numba-work-for-my-code
> 
> i think you may need to convert the polygons to numpy arrays first, but then i think it should be pretty fast...

I think with numba you don't even need to cast to array!

However to avoid introducing another dependency, a pure-numpy approach might be fast enough. It would just require using arrays more efficiently instead of appending to a list like I am doing now (it's fast enough for what I want to do).

**Pull request merged**
