### PR TITLE
Refactor xmin to dxmin

### PR DESCRIPTION
**Pull request by joamatab**

### CODE REVIEW

**Comment by tvt173** [comment]
when trying to pull the gds files to run the tests:
image

why don't we set the default max cell name length to 32? that's the limit for older tools, and what value does a cell name longer than that bring anyways? anything longer than 32 characters is pretty much unreadable, no?

**Comment by joamatab** [comment]
sorry, i was on the plane, now it should be better

**Comment by tvt173** [comment]
i still get the error when pulling the test gds files
image

**Comment by sebastian-goeldi** [comment]
Looks good to me, but didn't test yet

**Pull request merged**
