### PR TITLE
Allow single function as argument to `@gf.cell(post_process=...)`

### PR DESCRIPTION
**Pull request by nikosavola**
@joamatab, was there a specific reason it was not like this before?

### CODE REVIEW

**Comment by joamatab** [comment]
Hi Niko

if @sebastian-goeldi  is okay allow this in kfactory side im good with it :)

**Comment by sebastian-goeldi** [comment]
I don't see the big advantage of allowing single values. What does it give except a harder to read signature?

I would even argue for this over the current one:
`post_process: Sequence[Callable[[Component],None] = []`

**Comment by flaport** [comment]
I agree with @sebastian-goeldi . Allowing a well defined list is much clearer. No advantage in allowing a single function. I think we should start to follow such a philosophy more within gdsfactory anyway going forward. Best to have just one way to do things.

**Comment by joamatab** [comment]
i'll close this for now then

**Comment by sebastian-goeldi** [comment]
Also, these more convoluted types make it harder for static type.checkers like mypy to figure out what the actual type is after guarding and converting a variable (at some point you need to essentially use `cast(IntendedType, my_var)` on more or less every occurance (which can be tedious), or you do something like `my_new_vare: IntendedType = cast(IntendedType, my_var)` which can also be annoying.

I am happy to help withmaking it pass mypy or whatever static type checker once we are at 8.0

**Pull request closed without merging**
