### PR TITLE
better naming

### PR DESCRIPTION
**Pull request by joamatab**
avoid even when users don't use decorator to not create duplicated cell names so we can use the name as a component unique id and avoid slow geometric hashes

fixes https://github.com/gdsfactory/gdsfactory/issues/2435

@yaugenst 
@tvt173 
@nikosavola 
@flaport

### CODE REVIEW

**Comment by joamatab** [comment]
this seems PR seems to have issues with components that use `flatten_invalid_refs`

See for example `gf.components.coupler_bent`
image

**Comment by tvt173** [comment]
see the alternative branch, which is now working https://github.com/gdsfactory/gdsfactory/pull/2453

**Comment by joamatab** [comment]
Thank you Troy, i brought your improvements here

i prefer this PR because gf.Component() has a safer init name with the counter on it

**Comment by joamatab** [comment]
for some weird reason tests now fail in macOs but pass on linux

https://github.com/gdsfactory/gdsfactory/actions/runs/7459521790/job/20295712487

**Pull request merged**
