### PR TITLE
Add more tests

### PR DESCRIPTION
**Pull request by MatthewMckee4**
## Summary by Sourcery

Improve test coverage for `FileWatcher` and add support for routing NxN components south.

Enhancements:
- Simplify `LayerView` dictionary representation.
- Improve type hints for `Port` orientation and `route_south` excluded ports.
- Update `KLayoutTechnology` to handle enum layer maps and improve MEBES configuration.
- Enhance `strip_xml` to handle text nodes and elements.
- Refine `sort_ports` logic for consistent port ordering.

Tests:
- Add tests for `FileWatcher` run loop, file move, create, delete, and modify events.
- Add tests for routing NxN components south.
- Add tests for routing with bend and auto taper.
- Add tests for routing with invalid type and empty ports.
- Add tests for routing with port names and IO gratings.
- Add tests for `LayerView` string representation.
- Add tests for `strip_xml` function.
- Add tests for `sort_ports` function.
- Add tests for routing waypoints with NumPy arrays.
- Add tests for `check_ports_have_equal_spacing`, `direction_ports_from_list_ports`, and `get_list_ports_angle`.
- Add tests for `lyp_to_dataclass` function.
- Add tests for `route_single_sbend` with non-orthogonal ports.
- Add tests for `ensure_six_digit_hex_color` function.

### CODE REVIEW

**Comment by MatthewMckee4** [comment]
@joamatab Do you know why the test_to_svg sometimes fails?

**Comment by joamatab** [comment]
We recently added it

maybe we need to make sure the tmp folder exists before writing it

**Comment by joamatab** [comment]
i pushed something that may help with this

**Review by joamatab — APPROVED** [review]

**Comment by MatthewMckee4** [comment]
Happy for this to be merged too, cov up to 74%. I think it would be more but cov is not detecting some lines that are run, not sure why

**Comment by joamatab** [comment]
Looks great, this increases coverage to 74% 

great work Matthew!

**Pull request merged**
