### PR TITLE
add space parameter to via

### PR DESCRIPTION
**Pull request by HelgeGehring**
It would be nice to allow setting the space between vias, as that's usually closer to the DRC rules and changing the length of a via wouldn't necessitate a change in the spacing-parameter.

As there might be a better name for the new parameter to avoid confusion, I mark the PR as draft

### CODE REVIEW

**Comment by HelgeGehring** [comment]
@simbilod 
@joamatab

**Comment by joamatab** [comment]
How about calling it gap?

that way we are consitent with other similar parameters?

**Comment by HelgeGehring** [comment]
Sounds good!

**Comment by joamatab** [comment]
just released 6.54.0

**Pull request merged**
