### PR TITLE
Pathlength analyzer

### LINKED ISSUE #1814: path length extractor
How can we have an automatic path length extractor graph visualizer?

ideally it would take the netlist and compute the number of bends and total straight

### PR DESCRIPTION
**Pull request by tvt173**
This PR adds a pathlength analysis tool, which will allow you to visually explore and compare pathlengths in a circuit, broken down by cross section type. Other useful statistics such as # bends are also reported. I've added an example to the notebook on rib to strip autotransitioning showing how the tool can be used on a circuit with mixed cross-section types.

The tool requires that a `route_info` dictionary be added to the `info` of any component which you would like to consider as a routing element. I've added this to a few of the fundamental generic pdk components to make them compatible. Non-routing elements (and cells which are not decomposable into routing elements) are treated as black-boxes by default, creating breaks in the paths. However, you can optionally specify a connectivity function, which you can use to specify port-port pathlengths for generic components. There is one such function `idealized_mxn_connectivity` defined already, which you can try out.

The outputs of the tool are both a csv table of info about the routes and a static, interactive html page generated with bokeh. Please see snapshots below, and try the notebook to see it in action. The webpage contains both a stick diagram of the circuit and a summary table. The two are cross-linked for easy exploration.
pathlength_report

Closes #1814

### CODE REVIEW

**Comment by joamatab** [comment]
Looks great Troy,

- how about moving it to `plugins/path_extractor.py` ?
- it requires `pytest --force-regen`

**Comment by tvt173** [comment]
sure... i can move it and regenerate references if you're ok with the edits that add `route_info` to the basic components. other basic routing components will also need the same to be compatible

**Comment by joamatab** [comment]
Hi Troy, 

the pathlength file seems to be missing

**Comment by tvt173** [comment]
Oops, that's what I get for rushing 😛

Files should be there now

**Pull request merged**
