### PR TITLE
give attributes of crosssection to transition

### PR DESCRIPTION
**Pull request by simbilod**
necessary for https://github.com/gdsfactory/ubc2/pull/11

There was a time where Transition inherited from CrossSection, not sure why this is not the case anymore

Here I just copied over the attributes and functions that were required. 

In general it might be useful for a Transition to hold radius information (it could be that a bent transition supports a different bend radius than either composing cross section), as well as bbox and pins

### CODE REVIEW

**Comment by joamatab** [comment]
Hi Simon, 

why not use `gf.path.extrude_transition`?

**Comment by simbilod** [comment]
> Hi Simon, 
> 
> why not use `gf.path.extrude_transition`?

That's fine, but it means we can only use transitions directly with paths and not pass them as cross section arguments directly into predefined components

I.e. if I want to draw a sbend with a transition, I have to define my own sbend and cannot use the conponent

Is this the desired behavior?

**Comment by joamatab** [comment]
yes, you are right, great catch :)

See PR
https://github.com/gdsfactory/gdsfactory/pull/2243
with the fix for this

**Comment by simbilod** [comment]
Nice!

**Pull request closed without merging**
