### PR TITLE
add devsim

### PR DESCRIPTION
**Pull request by joamatab**
- add devsim

### CODE REVIEW

**Comment by joamatab** [comment]
Thank you Juan @tcaduser

**Comment by tcaduser** [comment]
Hi @joamatab,
Please note that I have not done a release to the main pypi index.  An explicit dependency on MKL adds a rather huge dependency (~1 GB) for users who may not be using devsim (~5 MB).  I can stage a release sometime next week.

**Comment by tcaduser** [comment]
FWIW, devsim can use either the MKL or be configured at runtime to use another version of BLAS/LAPACK.  This is through the DEVSIM_LIBS environment variable:
https://devsim.net/releasenotes.html#explicit-math-library-loading
The DEVSIM_LIBS environment variable is only needed when an MKL installation is not in the library path.

**Comment by tcaduser** [comment]
My understanding is that Anaconda on Windows platforms may not have an alternative math library available, and I haven't explored the availability on pip.

Without MKL, the solver switches from Intel MKL Pardiso, to SuperLU, which may result in slightly different numerical results.  As of now, I have only been regressing DEVSIM with Pardiso.

**Pull request merged**
