### PR TITLE
pydantic2 migration

### PR DESCRIPTION
**Pull request by joamatab**
All tests passing now

had to disable `@validate_arguments`

@alibillalhammoud 
@tvt173

### CODE REVIEW

**Comment by joamatab** [comment]
We are wating now for the rest of the plugins to port

- [x] kfactory
- [ ] meow
- [ ] sax
- [ ] tidy3d

**Comment by tylerflex** [comment]
FYI All future releases of `tidy3d` will use pydantic v2. We went with the approach of importing `pydantic.v1` and replacing `pylint` with `ruff`.

**Comment by flaport** [comment]
SAX ported (using `pydantic.v1` for now). Next week I'll tackle meow.

**Comment by joamatab** [comment]
Moved to https://github.com/gdsfactory/gdsfactory/pull/2038

**Pull request closed without merging**
