### PR TITLE
Fix MyPy issues in export folder

### PR DESCRIPTION
**Pull request by MatthewMckee4**
## Summary by Sourcery

Fix MyPy type issues in the export folder by updating type annotations and adding necessary type ignores to improve type safety.

Bug Fixes:
- Fix MyPy type issues in the export folder by updating type annotations and adding necessary type ignores.

Enhancements:
- Improve type safety by refining type annotations across multiple functions, including 'to_stl', 'get_polygons_points', and 'to_np'.

### CODE REVIEW

**Comment by joamatab** [comment]
looks great, why are the docs failing?

**Comment by MatthewMckee4** [comment]
Looking into it now

**Comment by MatthewMckee4** [comment]
Think this is failing due to the recent changes to [test-data](https://github.com/gdsfactory/gdsfactory-test-data.git )

**Review by joamatab — APPROVED** [review]
Looks great Matthew!

**Pull request merged**
