### PR TITLE
Repair symmetries for Tidy3D

### LINKED ISSUE #1681: `port_symmetries` on `gtidy3d.write_sparameters` seem broken
**Describe the bug**
When using port symmetries it seems to execute the wrong simulations and not copy over the s-parameters correctly

**To Reproduce**
```python
c = gf.components.mmi2x2()
symmetry = {
  "o1": {
    "s11": ["s22","s33","s44"], "s21": ["s12","s34","s43"], "s31": ["s13","s24","s42"], "s41": ["s14","s23","s32"],
  }
}
df = gt.write_sparameters(c, overwrite=True, port_symmetries=symmetry, is_3d=False, verbose=True)
```

**Expected behavior**
Execute a single simulation (not three) and copy the s-parameters as advised by the dict.

**Suggested fix**
I will open a PR

### PR DESCRIPTION
**Pull request by Jan-David-Black**
fixes #1681

### CODE REVIEW

**Comment by joamatab** [comment]
Thank you jan-David

**Comment by joamatab** [comment]
Thank you Jan David!

**Comment by Jan-David-Black** [comment]
My Pre-Commits seem broken and I didn't notice, sorry.

**Comment by joamatab** [comment]
it's okay, just fixed them

**Pull request merged**
