### PR TITLE
Add more tests

### PR DESCRIPTION
**Pull request by MatthewMckee4**
There is lots of uncovered code so I'm trying to add some more tests to increase coverage.

Not sure how people feel about [hypothesis](https://hypothesis.readthedocs.io/en/latest/) for testing, I've used it a lot and really recommend it, so will use it in this PR, can always return to not using it in future.

## Summary by Sourcery

Add `add_padding_to_size` and improve typing.

New Features:
- Add a new function `add_padding_to_size` to pad a component to a specific size.

Tests:
- Add new tests for padding functions using Hypothesis.

### CODE REVIEW

**Comment by MatthewMckee4** [comment]
Issues here are because of #3553

**Comment by joamatab** [comment]
is this ready to review?

**Comment by MatthewMckee4** [comment]
To keep this PR small, yeah sure.

**Comment by joamatab** [comment]
awesome,

this PR increases the coverage from 68 to 70%

image

**Review by joamatab — APPROVED** [review]
looks great! thank you Matthew!

**Pull request merged**
