### PR TITLE
remove klayout pin

### PR DESCRIPTION
**Pull request by joamatab**
- remove large GDS number layer from LAYER.WAFER  > 65535
- remove klayout pin

### CODE REVIEW

**Comment by jonbenfri** [comment]
I also ran into this issue when loading the generic KLayout layers file (``gdsfactory/generic_tech/klayout/layers.lyp``). I received the following error message:
```python
RuntimeError: Cannot write layer numbers larger than 65535 to GDS2 streams, writing cell 'Unnamed_0' in Cell.write
```

Was a fix for this supposed to make it into the latest version v8.9.0? Relevant commit: https://github.com/gdsfactory/gdsfactory/commit/7f1f57fb42d67305f375fd788c3ae17dcb35f552

It appears the fix did not make it into v8.9.0 since the value 99999 is still there for the WAFER layer:
https://github.com/gdsfactory/gdsfactory/blob/v8.9.0/gdsfactory/generic_tech/klayout/layers.lyp

Maybe I am reading things wrong, but commit page for the fix shows the v8.9.0 tag (see attached screenshot).

Screenshot_2024-09-28_17-52-50

For now, I manually changed the WAFER layer number to 999.

**Comment by leochand101** [comment]
Hey @jonbenfri  I made the update to the generic lyp file and I am still seeing the issue, any ideas ?
One additional complexity is I am using the sky130 module (or the components within them) not sure that has anything to do with it though. 
(gfsk130) chandru@Astra:/home/tools/skywater130/sky130$ grep "source" /home/chandru/.conda/envs/gfsk130/lib/python3.10/site-packages/gdsfactory/generic_tech/klayout/layers.lyp  | sort 
   <source>1000/0@1</source>
   <source>100/0@1</source>
   <source>101/0@1</source>
  <source>1/0@1</source>
   <source>110/0@1</source>
  <source>1/10@1</source>
  <source>111/0@1</source>
  <source>1/11@1</source>
   <source>1/12@1</source>
  <source>190/0@1</source>
  <source>191/0@1</source>
   <source>20/0@1</source>
  <source>201/0@1</source>
  <source>2/0@1</source>
  <source>202/0@1</source>
  <source>203/0@1</source>
  <source>204/0@1</source>
  <source>205/0@1</source>
  <source>206/0@1</source>
   <source>21/0@1</source>
   <source>22/0@1</source>
   <source>23/0@1</source>
   <source>24/0@1</source>
   <source>25/0@1</source>
   <source>26/0@1</source>
  <source>2/6@1</source>
   <source>27/0@1</source>
   <source>29/0@1</source>
  <source>2/9@1</source>
   <source>300/0@1</source>
   <source>301/0@1</source>
  <source>3/0@1</source>
   <source>302/0@1</source>
   <source>303/0@1</source>
   <source>304/0@1</source>
   <source>305/0@1</source>
   <source>305/0@1</source>
   <source>306/0@1</source>
   <source>307/0@1</source>
   <source>308/0@1</source>
   <source>309/0@1</source>
   <source>310/0@1</source>
   <source>311/0@1</source>
   <source>311/0@1</source>
  <source>3/1@1</source>
   <source>313/0@1</source>
   <source>315/0@1</source>
   <source>317/0@1</source>
   <source>319/0@1</source>
   <source>320/0@1</source>
   <source>321/0@1</source>
   <source>327/0@1</source>
   <source>330/0@1</source>
   <source>331/0@1</source>
  <source>34/0@1</source>
  <source>36/0@1</source>
  <source>3/6@1</source>
  <source>39/0@1</source>
   <source>399/0@1</source>
  <source>40/0@1</source>
  <source>4/0@1</source>
  <source>41/0@1</source>
  <source>42/0@1</source>
  <source>43/0@1</source>
  <source>44/0@1</source>
  <source>45/0@1</source>
  <source>46/0@1</source>
  <source>47/0@1</source>
  <source>49/0@1</source>
  <source>5/0@1</source>
  <source>6/0@1</source>
  <source>64/0@1</source>
  <source>65/0@1</source>
  <source>66/0@1</source>
  <source>67/0@1</source>
  <source>68/0@1</source>
  <source>69/0@1</source>
  <source>71/0@1</source>
  <source>72/0@1</source>
  <source>73/0@1</source>
  <source>733/0@1</source>
  <source>81/0@1</source>
   **<source>999/0@1</source>** Line changed
  <source>*/*@*</source>
  <source>*/*@*</source>
  <source>*/*@*</source>
  <source>*/*@*</source>

**Comment by jonbenfri** [comment]
Hi @leochand101, sorry but I do not have an idea for how to solve your issue.

I am not sure the gdsfactory generic pdk is relevant for your use case (gdsfactory/generic_tech/klayout/layers.lyp).

Perhaps the KLayout layout here is what you need to edit:
https://github.com/gdsfactory/skywater130/blob/main/sky130/klayout/layers.lyp

Could you please create a new issue in the gdsfactory skywater130 GitHub repository and continue the discussion there?
https://github.com/gdsfactory/skywater130

**Comment by leochand101** [comment]
@jonbenfri 

I already had opened a case there https://github.com/gdsfactory/skywater130/issues/109

BTW I have already checked for the [/sky130/klayout/layers.lyp] and there are no layers with numbers above 1000 
Also this is happening on all components not just sky130, I cant even run the basic notebook examples. Also it looks like these methods are being run through kfactory methods so its maybe an interaction between versions of kfactory and gdsfactory

```
>>> c
sky130_fd_pr__rf_nfet_0_75e56352: ports ['DRAIN', 'SOURCE', 'GATE', 'SUBSTRATE', 'GATE1', 'SUBSTRATE1'], 0 instances
>>> c.layers
[(65, 20), (67, 20), (66, 44), (67, 44), (68, 20), (68, 5), (68, 16), (69, 20), (69, 5), (69, 16), (95, 20), (93, 44), (66, 20), (66, 83), (94, 20), (65, 44), (68, 44)]
>>> c.show()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/leochand/.conda/envs/gdsfactory_sky130/lib/python3.10/site-packages/kfactory/kcell.py", line 1137, in show
    show(
  File "/home/leochand/.conda/envs/gdsfactory_sky130/lib/python3.10/site-packages/kfactory/kcell.py", line 7744, in show
    layout.write(str(tf), save_options)
  File "/home/leochand/.conda/envs/gdsfactory_sky130/lib/python3.10/site-packages/kfactory/kcell.py", line 1561, in write
    self._kdb_cell.write(str(filename), save_options)
RuntimeError: Cannot write layer numbers larger than 65535 to GDS2 streams, writing cell 'sky130_fd_pr__rf_nfet_0_75e56352' in Cell.write
```

**Comment by jonbenfri** [comment]
Hi @leochand101, thanks for including the working example showing the error details, and also the link to the issue you created in the gdsfactory/skywater130 repository.

Unfortunately, I still do not have an idea for how to solve your issue. If you have not tried this already, perhaps create a new conda environment. There may be some versions conflict happening.

**Pull request merged**
