### PR TITLE
Thermal disk

### PR DESCRIPTION
**Pull request by simbilod**
disk with thermal heater

image

### CODE REVIEW

**Comment by simbilod** [comment]
Having issues rebuilding the regressions locally, hopefully not too much of a problem

**Comment by joamatab** [comment]
Thank you Simon!

**Comment by joamatab** [comment]
just pushed some minimal improvements
https://github.com/gdsfactory/gdsfactory/commit/9f0f5881dfacdd44d192cb73ba95a860afef0520

- using typings instead of deprecated types
- adding @cell decorator

**Comment by simbilod** [comment]
> just pushed some minimal improvements [9f0f588](https://github.com/gdsfactory/gdsfactory/commit/9f0f5881dfacdd44d192cb73ba95a860afef0520)
> 
> * using typings instead of deprecated types
> * adding @cell decorator
> 
> and made a minor release

good calls thanks!

**Pull request merged**
