### PR TITLE
Meshing notebooks

### PR DESCRIPTION
**Pull request by simbilod**

### CODE REVIEW

**Comment by joamatab** [comment]
Hi Simon, it looks great,

docs are failing,
https://github.com/gdsfactory/gdsfactory/actions/runs/3610878027/jobs/6084961676

if you can't find i workaround i can disable the execution of the notebooks

**Comment by simbilod** [comment]
Let's disable, since pyvista and/or gmsh can have trouble running on headless systems

Before you merge, let me go back and add conditionals to load a precomputed image by default for the docs

**Comment by joamatab** [comment]
I don't think allowing errors on the docs is the way to go :)

**Comment by simbilod** [comment]
Haha yeah, just wanted to see if I could get more information from the check log this way. I'm not super familiar with debugging for these hooks. I'll revert now.

**Comment by simbilod** [comment]
Where is the doc building environment/container specified? Maybe we can try adding libGLU, and others, since that is what seems to be crashing right now?

`apt-get install libglu1-mesa libxi-dev libxmu-dev libglu1-mesa-dev`

**Comment by joamatab** [comment]
Sounds good 👍

**Pull request merged**
