### PR TITLE
fix windows installer

### LINKED ISSUE #904: fix windows releases
windows releases are failing now

https://github.com/gdsfactory/gdsfactory/actions/runs/3516082345/jobs/5892172732

how could we fix this? Im not sure what changed

### PR DESCRIPTION
**Pull request by joamatab**
Trying to fix #904 

need to check if this works

@simbilod 
@SkandanC 
@nikosavola

### CODE REVIEW

**Comment by simbilod** [comment]
Doesn't work for me, I keep getting kernel errors

**Comment by simbilod** [comment]
some file is not found

image

**Comment by simbilod** [comment]
It works if I use Spyder. Seems to be a JupyterLab/Notebook problem

**Comment by simbilod** [comment]
It also works on VSCode

**Comment by joamatab** [comment]
Are the packages installed now?

**Comment by simbilod** [comment]
> Are the packages installed now?

still partially problematic (on Windows at least) 

some work:

image

some don't:

image

You can always pip install yourself after to make it work:

image

**Pull request merged**
