### PR TITLE
Database

### PR DESCRIPTION
**Pull request by joamatab**
- add database for structured data for simulations and measurements

@tvt173 
@flaport 
@thomasdorch 
@SkandanC 
@proppy

### CODE REVIEW

**Comment by tvt173** [comment]
would be great if we can generate a diagram of the database to review
https://crashlaker.github.io/database/2020/05/13/database_diagram_with_python_sqlalchemy.html

**Comment by joamatab** [comment]
image

**Comment by joamatab** [comment]
I can merge it and then we can add documentation on how to add data to it into future PRs:

TODO:

- [ ] add examples on how to add and query measurements and simulations
- [ ] add examples on how to bring up and connect your own database

Maybe:

- [ ] Include GDS serialization (polygons and references)
- [ ] material database

**Comment by tvt173** [comment]
hi @joamatab , overall it looks good to me. the only part I have any immediate criticisms for are the port type:
image

you have `is_electrical` and `is_optical` as columns, but I think it would be cleaner and more flexible to have something like `port_type` which is either a string or maps to a table of port types. what do you think?

also, do you have or see value in adding a relation to a PDK name/version used to make the wafer? or otherwise to the version of the code used to generate it?

**Pull request merged**
