### PR TITLE
warn on bad bundles

### PR DESCRIPTION
**Pull request by tvt173**
hi @joamatab ,

This PR is meant to address #1992 .

It's not a particularly elegant way to do it, but I'm able to catch bad bundle configurations and invalidate them by checking that the ports are actually connected by the routes or not. If they're not, I raise a RouteWarning and draw error shapes instead of the routes.

Note: this PR can be a starting point, but it's still a work in progress

### CODE REVIEW

**Comment by joamatab** [comment]
Hi Troy,

this PR seems to affect other routes

image

**Comment by joamatab** [comment]
I think the code has some issues

for example in `gdsfactory/components/coh_rx_single_pol.py`
port_ordered seems correct and is warned as wrong

image

**Comment by tvt173** [comment]
yes, haven't worked through all the issues yet. can take another look later

**Comment by tvt173** [comment]
> Hi Troy,
> 
> Thank you for your PR
> 
> this PR seems to break some of the routes for the tests,
> 
> for routing to pads and grating couplers, we actually want to keep the old behavior How about adding a flag `enforce_port_order`?
> 
> image

I don't know if I agree with this. Could you explain? I think it's _very_ problematic if you say the connections should be
o1->o3
o2->o4
but instead you get
o1->o4
o2->o3
Especially because there is no feedback that this kind of swap has happened. In which scenarios is this kind of behavior beneficial?

**Comment by joamatab** [comment]
I think is beneficial if you want to automatically route all ports to pads and you don't care about the order

what do you think?

**Comment by tvt173** [comment]
i suppose if there are valid use cases for it, I am ok with keeping it as a flag. it could also be useful to debug the bundles with impossible ordering, to see the configuration which _is_ routable... but i think we should definitely enforce port order by default. it could be a very tricky and catastrophic bug if this happens without the user noticing. i see you've done this already in your edits 👍 . i'll take a deeper look to see if i can figure out why some of the test cases are failing

**Comment by tvt173** [comment]
@joamatab , I made some further fixes to both the code and the tests. please review and merge if you are satisfied.

note that i moved the new tests to `tests/routing/test_port_ordering.py`. also note that a few of those tests I am skipping for now because they fail for other reasons (shortcomings of the current autorouter)

**Comment by tvt173** [comment]
added issues #2003 and #2004 which would fix the currently skipped test cases

**Pull request merged**
