### PR TITLE
Add testcoverage (simple difftest)

### PR DESCRIPTION
**Pull request by Jan-David-Black**
Probably not the cleanest way to solve this: I just added a difftest with a component that is exported and imported with label markers.

### CODE REVIEW

**Comment by Jan-David-Black** [comment]
As far as I can see black doesn't like `mzi_lattice.py`. However, I didn't touch that...

**Comment by joamatab** [comment]
Thank you Jan David,

This PR also adds test coverage

https://github.com/gdsfactory/gdsfactory/pull/929

**Comment by Jan-David-Black** [comment]
Any Idea what I did wrong here? Asking to not repeat in the future

**Comment by joamatab** [comment]
I think we both added a test for this at the same time 

Diff test are slower

**Pull request closed without merging**
