### PR TITLE
Graphviz update

### PR DESCRIPTION
**Pull request by Jelly298**
Rewritten the schematic generation code to utilize a subgraph-based structure instead of the record-based structure. However, the graphviz orthogonal routing algorithm occasionally produces incorrect routing for certain ports.

## Summary by Sourcery

Enhancements:
- Refactor schematic generation to use a subgraph-based structure instead of a record-based structure for improved modularity and flexibility.

### CODE REVIEW

**Comment by joamatab** [comment]
i fixed the merge conflicts with main

What are the advantages of this PR?

the old schematics look a bit better


image

**Comment by sebastian-goeldi** [comment]
the big disadvantage in graphviz as I understand it is that you cannot indicate directionality (and size of nodes). It's not a big issue if you have a relatively well defined schematic such as an mzi or splitter tree. But I am pretty sure this will look pretty weird on a whole chip or even just a general PIC. Wouldn't it be easier to just draw each component according to its bounding box and connect them on points?

**Comment by Jelly298** [comment]
@joamatab The advantage of the PR is that it addresses the ortho routing algorithm issue within Graphviz. Currently, the ortho routing algorithm in Graphviz lacks the capability to handle bounding box collisions (the previous PR). As a workaround, I have been introducing calculated gaps artificially. I will try to thicken the lines and see if it improves the visualisation.

@sebastian-goeldi, are you suggesting that we do not render ports and solely focus on drawing the components? And maybe there is some confusion, but I could change the size of nodes in graphviz

**Comment by joamatab** [comment]
I see, for some reason the previous version looks still a bit better, is it possible to show only the port name,

- i think instanceName_portName is too long
- Ideally there is no gap between instance name and port


image

**Pull request closed without merging**
