### PR TITLE
Fix off-center fill

### LINKED ISSUE #2019: Component fill not centered for some arguments
**Describe the bug**
`fill_rectangle_custom()` produces a fill that is off center for some arguments

**To Reproduce**
```
import gdsfactory as gf

@gf.cell
def filled_component(size):
    c = gf.Component()
    c.add_ref(gf.c.rectangle((size, size), layer=(1, 0), centered=True))
    rect_comp = gf.c.rectangle((2, 2), layer=(1, 0), centered=True)
    fill_comp = gf.fill.fill_rectangle_custom(
        component=c,
        fill_cell=rect_comp,
        spacing=(3, 3),
        margin=1,
    )
    c.add_ref(fill_comp)
    return c


filled_component(13).show()  # components not centered
filled_component(12).show()  # components centered
```

**Expected behavior**
I'd expect the fill to be centered for all input arguments. This is likely a rounding edge case.

**Suggested fix**
`_raster_index_to_coords` needs to be updated along with the inverse function in `_rasterize_polygons`. I will submit a PR

### PR DESCRIPTION
**Pull request by zobristnicholas**
Fixes #2019

### CODE REVIEW

**Comment by zobristnicholas** [comment]
This actually doesn't work if the component is not centered..

**Comment by zobristnicholas** [comment]
Nevermind, I fooled myself. The below code shows that everything is working correctly.

```
import gdsfactory as gf


@gf.cell
def filled_component(size, centered=False):
    c = gf.Component()
    c.add_ref(gf.c.rectangle((size, size), layer=(1, 0), centered=centered))
    rect_comp = gf.c.rectangle((2, 2), layer=(1, 0), centered=True)
    fill_comp = gf.fill.fill_rectangle_custom(
        component=c,
        fill_cell=rect_comp,
        spacing=(3, 3),
        margin=1,
    )
    c.add_ref(fill_comp)
    return c


filled_component(13, True).show()
filled_component(12, True).show()
filled_component(13, False).show()
filled_component(12, False).show()
```

**Comment by zobristnicholas** [comment]
Sorry, I meant everything is working correctly with the fix from this PR. If you agree, we should merge this

**Comment by joamatab** [comment]
Some checks are still failing

**Comment by joamatab** [comment]
merged! thank you Nicholas!

**Pull request merged**
